version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd .\github-to-lambda-demo\
      - zip -r java_function.zip Simple.jar
  post_build:
    commands:
      - echo "Updating lambda Function.."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://java_function.zip
      - aws s3 cp java_function.zip s3://myuniquebucket-2023/java_function.zip
      - echo "Lambda function zip file uploaded to S3"
      - echo "DONE!"